### ISSUE TITLE
Handling 500s

### ISSUE THREAD

**Issue by excid3** [jorgemanrubia/turbolinks_render#1]
This gem works great, aside from errors getting clobbered when something fails. If you render a 500 error, nothing happens client side.

Is there an easy way to catch 500 errors and render the Rails error page instead?

**Comment by jorgemanrubia** [comment]
Hi @excid3,

Sorry for the delay here, I had missed this one. You are right, it would be good to handle those 500 errors, thanks for pointing it out. I will try to poke around and see how to attack that. Of course, if anyone wants to help, PR are welcomed 😬.

Thanks!

**Comment by excid3** [comment]
A quick prototype of this works-ish.

```ruby
module ActionDispatch
  # This middleware is responsible for logging exceptions and
  # showing a debugging page in case the request is local.
  class DebugExceptions

    def render_for_browser_request(request, wrapper)
      template = create_template(request, wrapper)
      file = "rescues/#{wrapper.rescue_template}"

      if request.xhr?
        html = template.render(template: file, layout: "rescues/layout")
        body = build_turbolinks_response_to_render(html)
        format = "text/javascript"
      else
        body = template.render(template: file, layout: "rescues/layout")
        format = "text/html"
      end
      render(wrapper.status_code, body, format)
    end

    def build_turbolinks_response_to_render(html)
      escaped_html = ActionController::Base.helpers.j(html)

      <<-JS
    (function(){
      Turbolinks.clearCache();
      var parser = new DOMParser();
      var newDocument = parser.parseFromString("#{escaped_html}", "text/html");
      document.documentElement.replaceChild(newDocument.body, document.body);
      Turbolinks.dispatch('turbolinks:load');
      window.scroll(0, 0);
    })();
      JS
    end

  end
end
```

This will inject the error page as a Turbolinks view, with a few problems:

- [ ] CSS should be cleared from the main app, only CSS from the error page should show
- [ ] web-console doesn't get injected, needs override too
 https://github.com/rails/web-console/blob/master/lib/web_console/middleware.rb#L57
- [ ] Pull this render code to a module so we can reuse it between this class and the existing render?

**Comment by excid3** [comment]
web-console can be enabled easily, but it assumes the response is an HTML response unfortunately. It will just append HTML to the end of our JS response.

```
module WebConsole
  class Middleware

    def acceptable_content_type?(headers)
      [Mime[:html], Mime[:js]].include? Mime::Type.parse(headers["Content-Type"].to_s).first
    end

  end
end
```

**Comment by jorgemanrubia** [comment]
Thanks @excid3 🙏 , I'll look into it this weekend.

**Comment by jorgemanrubia** [comment]
Hi @excid3,

This was fixed in version `0.9.9`. I changed the internals quite a bit in this version, I'd appreciate if you can confirm all is good on your end. Thanks 🙏

Cheers

**Comment by excid3** [comment]
Seems to be working great @jorgemanrubia! Thanks for all that work! 🤘

**Comment by jorgemanrubia** [comment]
Thanks @excid3! Make sure you update to latest if you updated to `0.9.9` (it introduced a few problems fixed later today).

**Comment by excid3** [comment]
Looks like the latest is working smoothly! 👍
