### ISSUE TITLE
Add option to retain scroll position

### ISSUE THREAD

**Issue by andreaslillebo** [jorgemanrubia/turbolinks_render#17]
On pages where the form is located at the bottom of the page, e.g. a sign-up form located under an article, it would be nice to be able to submit the form without the browser scrolling to the top of the page (and the sign-up form disappearing from view).

This is the line causing the page to scroll to the top:
https://github.com/jorgemanrubia/turbolinks_render/blob/86e7a890c907179dea0aa11d5c9159e0cc1fce5d/lib/turbolinks_render/middleware.rb#L62

Possible places to define this option:
- as a global option with in initializer
- as a data attribute on the form tag
- as an option passed to `render`

If you're interested, I could try and put together a PR for this.

**Comment by jorgemanrubia** [comment]
Hi @andreaslillebo,

Thank you for your feedback.  I have mixed feelings about including scroll management here, as this gem focuses on using `render` with Turbolinks. I see keeping the scroll in place as something more horizontal. Also, unless visiting an anchor link, [Turbolinks will scroll to the top of the page](https://github.com/turbolinks/turbolinks/blob/2f7cd3247f28152458e5f45ff281d8ec7b1f8f47/README.md#application-visits) so the implementation here is consistent with Turbolinks. 

In the past, I have made scroll persist with [some variation of this approach](https://stackoverflow.com/a/51790464). I would use something like that. With little code you can have a general-purpose system in place you can opt-in for persisting code.

Making such system a reusable javascript module would be a nice project (there seem to be a need for it). 

Thanks again for your interest in improving `turbolinks-render`

**Comment by andreaslillebo** [comment]
Thanks for your reply.

I can see how this could be outside the scope of this gem, and how scrolling to the top is consistent with how Turbolinks works.

I tried your suggested approach to [persist the scroll position](https://stackoverflow.com/a/51790464). It keeps the scroll-position, but the page jitters when submitting the form (as if Turbolinks first scrolls to the top, then back down to the correct position in a fraction of a second).

The ideal would be to find a way to intercept the Turbolinks response and remove the `window.scroll(0, 0);`-line.

**Comment by jorgemanrubia** [comment]
@andreaslillebo I wonder if switching the order of these 2 lines would fix the visual glitch: https://github.com/jorgemanrubia/turbolinks_render/blob/86e7a890c907179dea0aa11d5c9159e0cc1fce5d/lib/turbolinks_render/middleware.rb#L61-L62. If it does, I'd be happy to make that change.

**Comment by andreaslillebo** [comment]
That worked!

I tried switching those two lines and the visual glitch is gone. Thank you so much.

**Comment by jorgemanrubia** [comment]
Nice! I just released 0.9.16 including this tweak.
