### ISSUE TITLE
Returned <script> tags are not executed

### ISSUE THREAD

**Issue by omitter** [jorgemanrubia/turbolinks_render#4]
If a response contains script tags they are not executed, in contrast to usual Turbolinks responses.

It looks like `activateBodyScriptElements` [here](https://github.com/turbolinks/turbolinks/blob/v5.2.0/src/turbolinks/error_renderer.coffee) would do the job, but I couldn't get it to run (also can't see why it's in **Error**Renderer…).

**Comment by jorgemanrubia** [comment]
Thanks for reporting this @omitter and for the potential solution. I'll see if I can fix this shortly.

**Comment by jorgemanrubia** [comment]
Hi @omitter,

This was fixed in version `0.9.9`. I changed the internals quite a bit in this version, I'd appreciate if you can confirm all is good on your end. Thanks 🙏

Cheers

**Comment by omitter** [comment]
I did a quick test and with 0.9.10 it's working fine. Thanks a lot!
