### ISSUE TITLE
Any plan to make it compatible with Hotwire ?

### ISSUE THREAD

**Issue by bdavidxyz** [jorgemanrubia/turbolinks_render#42]
Hotwire supports rendering for the error case only, so I think there is still a space for a turbo_render gem.

**Comment by jorgemanrubia** [comment]
Hi @bdavidxyz, not really. I would now go with vanilla Hotwire. That `turbo_render` gem might have its use, but probably as a different gem. I have no plans in evolving `turbolinks_render` to cover that.
