### ISSUE TITLE
Rails 6 support

### ISSUE THREAD

**Issue by calebwoods** [jorgemanrubia/turbolinks_render#5]
Because the gemspec specifies '~> 5.2' for Rails it is not possible to use this Rails 6 beta.

**Comment by jorgemanrubia** [comment]
Thanks for pointing it out @calebwoods. I intend to do some work on the gem this weekend so I'll fix this.

**Comment by jorgemanrubia** [comment]
Addressed in #2. I will push a new version this weekend. Thanks
